# -*- coding: utf-8 -*-
"""Practical 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VNuOf4YKitOMHluj5Eyz72N_y7XV-kz4

4. Write a function that takes a number (>=10) as an input and return the digits of the number as a set.
"""

ar=[]
def digits():
  n=int(input("Enter the number : Should be greater than 10 "))
  if n<10:
    print("Wrong input!!")
  n=abs(n)
  while n > 0:
    p=int(n%10)
    ar.append(p)
    n=n//10
  return ar
set=digits()
set.reverse()
print(set)