# -*- coding: utf-8 -*-
"""Question 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QNZSPqmOKsQvfwwQB9Vy6p-P_iDadQqW

2. Consider a showroom of electronic products, where there are various salesmen. Each salesman is given a commission of 5%, depending on the sales made per month. In case the sale done is less than 50000, then the salesman is not given any commission. Write a function to calculate total sales of a salesman in a month, commission and remarks for the salesman. Sales done by each salesman per week is to be provided as input. Use tuples / list to store data of salesmen.
Assign remarks according to the following criteria: Excellent: Sales >=80000
Good: Sales>=60000 and <80000
Average: Sales>=40000 and <60000 Work Hard: Sales < 40000
"""

def accounts():
  name=input("Enter the name of the salesman")

  sales=int(input("Enter the sales in week 1"))
  sales+=int(input("Enter the sales in week 2"))
  sales+=int(input("Enter the sales in week 3"))
  commission=0.0;remarks=" "
  if sales>50000:
    commission=sales*0.05
  if sales>=80000:
    remarks="Excellent"
  elif sales>=60000 and sales<80000:
    remarks="Good"
  elif sales>=40000 and sales<60000:
    remarks="Average"
  elif sales<40000:
    remarks="Work Hard"
  
  tri=(name,sales,commission,remarks)
  return tri

tup=accounts()
print("Name of salesman : ",tup[0])
print("Total sales : ",tup[1])
print("Commission of the salesman : ",tup[2])
print("Remarks : ",tup[3])