# -*- coding: utf-8 -*-
"""Question 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DoSUf_lmPn8fkEDlOA9zRSg86ERY2HyD

1. Write a function that takes the lengths of three sides: side1, side2 and side3 of the triangle as the input from the user using input function and return the area and perimeter of the triangle as a tuple. Also, assert that sum of the length of any two sides is greater than the third side.
"""

import math

def triangle():
  a=int(input("Enter side 1 "))
  b=int(input("Enter side 2 "))
  c=int(input("Enter side 3 "))
  s1=a+b;
  s2=b+c;
  s3=a+c;

  if s1>c and s2>a and s3>b:
    print("Sum of length of any two sides is always greater than the third")
  else:
    print("Assertion turned out false")

  perimeter=a+b+c;
  s=perimeter/2;
  area=math.sqrt(s*(s-a)*(s-b)*(s-c))
  tri=(perimeter,area)

  return tri


tup=triangle()
print("Perimeter : ",tup[0])
print("Area : ",tup[1])