# -*- coding: utf-8 -*-
"""Question5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QuLn1doV966vTsZv3Wo_0nncYyMX77Xm
"""

import Question3 as q

def pattern(n,y):
  for x in range(2,n):
    global sum
    q=x/2
    if q%2==0:
      sum+=y*x/q.fact(x)
    else:
      sum-=y*x/q.fact(x)
  return sum

n=int(input("Enter the number of terms "))
y=int(input("Enter the value of x"))
sum=0;
sum1=1-pattern(n,y) 
print("The sum of the pattern is ",sum1)

cd drive/MyDrive/Python\ Practicals

!pip install import-ipynb
import import_ipynb