# -*- coding: utf-8 -*-
"""Question_9_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JWsnwE0ueM3ARpmWbHPsOCCV0GQzsOaS
"""

num_students = int(input("Please enter number of students:"))
print("you entered %s students" %num_students)
student_info = {}
student_data = ['Math marks : ', 'Physics marks : ', 'Chemistry marks : ']
for i in range(0,num_students):
    student_name = input("Name :")
    student_info[student_name] = {}
    for entry in student_data:
        student_info[student_name][entry] = int(input(entry)) #storing the marks entered as integers to perform arithmetic operations later on.
#print student_info
print("Please enter student name ?")
name = input("Student name : ")
if name in student_info.keys():
    print("Average student marks : ", str(sum(student_info[name].values())/3.0))
else:
    print("please enter valid name")