# -*- coding: utf-8 -*-
"""Question 8(python).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OGXGRPzCgo2r6nJEdIQyiHdhI_ZZ9qJj

8. Write a Python program to perform the following using list:
a) Check if all elements in list are numbers or not.
b) If it is a numeric list, then count number of odd values in it.
c) If list contains all Strings, then display largest String in the list.
d) Display list in reverse form.
e) Find a specified element in list.
f) Remove the specified element from the list.
g) Sort the list in descending order.
h) accept 2 lists and find the common members in them.
"""

def num(a):
  l=len(a)
  counter=0
  for x in a:
    if type(x)==int or type(x)==float:
      counter+=1
  if counter==l:
    print("All the numbers are integer")
  else:
    print("All numbers are not integers")
  return counter

def odd(a):
  c=0
  if num(a)==len(a):
    for x in a:
      if x%2!=0:
        c+=1
    print(c)
        
def string(a):
  c=0
  d=[]
  for x in a:
    if type(x)==str:
      c+=1
      d.append(len(x))
    if c==len(a):
      k=0
      m=0
      for i in range(0,len(d)):
          if m<d[i-1]:
            m=d[i-1]
            k=i-1
      print(a[k])

def reverse(a):
  a.reverse()
  print(a)

def search(a,x):
  for y in a:
    if y==x:
      print("Element found")
      return
  print("Element not found")    

def rem(a,x):
  a.remove(x)
  print(a)

print('**MENU*')
print('\n1.Check if all the elements in list are numbers or not\n2.In numeric list,count odd values')   
print('3.In string list,display largest string\n4.Reverse the list\n5Find a specified element in the list')
print('6.Remove the specified element in the list\n7.Sort the list in descending order\n8.find the common members in two list\n9.Exit from the program')
n=int(input('\n Enter the size of list'))
a=[]
for x in range(0,n):
  f=input("Enter the value")
  a.append(f)

ch=int(input('Enter your choice: '))  
if ch==1:
  num(a)
elif ch==2:
  odd(a)
elif ch==3:
  string(a)
elif ch==4:
  reverse(a)
elif ch==5:
  x=input("Enter the value to be searched")
  search(a,x)
elif ch==6:
  x=input("Enter value to be deleted")
  rem(a,x)
else:
  print("wrong input")

def check_List(num_list):
  c=0
  for x in num_list:
    if (type(x)==int or type(x)==float):
      print('List has ',x,'= It is number')
      c=c+1
    else:
      print('List has ',x,' = It is not  number')
  return c   
  

def odd_values(list1):
  count=check_List(list1)
  if(count==len(list1)):
    c1=0;
    c2=0;
    for x in list1:
    
      if x%2==0:
        print(x,'= Even value')
        c1=c1+1
      else:
         print(x,'= Oddvalue')
         c2=c2+1
    print('Number of Even values:',c1)
    print('Number of Odd values: ',c2)
  else:
    print('It is not numeric List')  


def check_strings(list1):
  c=0
  for x in list1:
    if(type(x)==str):
      c=c+1;
    else:
      print(x,'not a string')  
  if(c==len(list1)):
    max=len(list1[1])
    print('It is string list')
    for x in list1:
      if(max<len(x)):
        max=len(x)
        res=x 
    print('Largest string: ',res)        
  else:
    print('List containing other types than string')  
     
 
def reverse_list(list1):
  list1.reverse()
  return list1

def search_el(list1,n):
  flag=0
  for x in range(len(list1)):
    if(list1[x]==n):
      flag=1
      index=x
  
  if (flag==1):
    print('element found at index',index)
  else:
    print('Element not found')         


def remove_el(list1,n):
  for x in list1:
    if(x==n):
      list1.remove(n)
  print('Now the list',list1) 
 

def sort_des(list1):
  list1.sort(reverse=True)
  print(list1)  


def common(list1,list2):
  l3=[]
  n=0
  for x in list1:
    for y in list2:
      if(x==y):
        l3.append(x)
        n=n+1
  print(l3)      
  print('Number of common elements',n)      
  print('No more common elements')      
while(True):
  print('**MENU*')
  print('\n1.Check if all the elements in list are numbers or not\n2.In numeric list,count odd values')   
  print('3.In string list,display largest string\n4.Reverse the list\n5Find a specified element in the list')
  print('6.Remove the specified element in the list\n7.Sort the list in descending order\n8.find the common members in two list\n9.Exit from the program')
  ch=int(input('Enter your choice: '))  
  if ch==1:
    l=[1,2,3,4,10,6,9.0]
    count=check_List(l)
    if(count==len(l)):
      print('All the elements in list are numbers') 
    else:
       print('All the elements are not numbers')    
  if ch==2:
    l=[1,2,3,4,18,6,9.0]
    odd_values(l)
  if ch==3:
    l=['my','name',89
       ,'sakshi'] 
    check_strings(l) 
  if ch==4:
    l=[1,2,3,4,5,6,7]
    print('Reverse of the string',reverse_list(l)) 
  if(ch==5):
    l=[]
    n=int(input('How mant elements in the list'))
    for x in range(n):
      ele=input('Enter the element: ')
      l.append(ele)
    num=input('Enter the element you want to search: ')
    search_el(l,num)  
  
  if ch==6:
    l=[]
    n=int(input('How mant elements in the list'))
    for x in range(n):
      ele=input('Enter the element: ')
      l.append(ele)
    num=input('Enter the element you want to remove: ')
    remove_el(l,num) 
  if ch==7:
     l=[]
     print('You want to enter string list or numeric')
     ch=int(input('Enter your choice: \n1.String list\n2.numeric list'))
     if(ch==1):
       n=int(input('How mant elements in the list'))
       for x in range(n):
         ele=input('Enter the elements in string: ')
         l.append(ele)
       sort_des(l) 
     if(ch==2):
         n=int(input('How mant elements in the list'))
         for x in range(n):
           ele=int(input('Enter the elements in string: '))
           l.append(ele)
         sort_des(l) 

   
  if ch==8:
    l1=['sakshi','sharma',90,100]
    l2=['sharma',100]
    common(l1,l2)  
  if ch==9:
    break