# -*- coding: utf-8 -*-
"""Question 7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1huqEq0nEvlCjWNr01p9HQPyjLJHhjg3Q

7. Write a menu driven program to perform the following on strings:
a) Find the length of string.
b) Return maximum of three strings.
c) Accept a string and replace all vowels with “#”
d) Find number of words in the given string.
e) Check whether the string is a palindrome or not.
"""

#Ques7
def length(a):
  l=len(a)
  return l


def maximum(a,b,c):
  a1=len(a)
  b1=len(b)
  c1=len(c)
  if(a1>b1 and a1>c1):
    return a
  elif(b1>a1 and b1>c1):
    return b
  elif(c1>a1 and c1>b1):
    return c
  else:
    print('Some string are equals!')       
  print('Length of string 1=',a1)
  print('Length of string 2=',b1) 
  print('Length of string 3=',c1)


def replace(a):
  k="#"
  for i in range(len(a)):
    if(a[i]=='a'or a[i]=='A' or a[i]=='e'or a[i]=='E' or a[i]=='i'or a[i]=='I' or a[i]=='o'or a[i]=='O' or a[i]=='u'or a[i]=='U'):
      a=a.replace(a[i],k)
  print(a)    


def no_of_words(a):
  n=len(a.split())
  return n


def Pallindrome(a):
  str1=''
  for i in a:
    str1=i+str1
  print('Reverse of string:',str1)  
  if(a==str1):
    print('String is palindrome!!')
  else:
    print('String is not palindrome!!')  

    
while(True):

   print('**MENU*') 
   print('\n1.Find length of the string\n2.Maximum of the Strings\n3.Replace vowels with "#"\n4.Find number of word in given string\n5.check whether the the string is pallindrome or not:')
   print('6.Exit from the program')
   ch=int(input('Enter your choice: '))
   
   if(ch==1):
     a=str(input('Enter the string!: '))
     print('Length of the given string: ',end=" ")
     print(length(a))
  
   elif(ch==2):
     str1=str(input('Enter first string:  '))
     str2=str(input('Enter second string: '))
     str3=str(input('Enter third string:  '))
     print('Maximum of the three strings: ',end=" ")
     print(maximum(str1,str2,str3))
  
   elif(ch==3):
    a=str(input('Enter the string!: '))
    print('New string will be: ',end=" ")
    replace(a)
  
   elif(ch==4):
    a=str(input('Enter the string!: '))
    print('Number of words in given string: ',end=" ")
    print(no_of_words(a))
   elif(ch==5):
    a=str(input('Enter the string!: '))
    Pallindrome(a)
   elif ch==6:
    break;