# -*- coding: utf-8 -*-
"""Question 6(python).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eE3FH0BpdyWDVmCHlFlOC4hYD2Ljsq61

6. Consider a tuple t1={1,2,5,7,9,2,4,6,8,10}. Write a program to perform following
operations:
a) Print another tuple whose values are even numbers in the given tuple.
b) Concatenate a tuple t2={11,13,15) with t1.
c) Return maximum and minimum value from this tuple.
"""

t1=(1,2,5,7,9,2,4,6,8,10)
i=0
t3=[]
for x in t1:
  if x%2==0:
    t3.append(x)
print("Even values: ",tuple(t3))

t2=(11,13,15)
t4=[]
for x in t1:
  t4.append(x)
for y in t2:
  t4.append(y)
print("After concatenation: ",tuple(t4))

print("Maximum value: ",max(t4))
print("Minimum value: ",min(t4))