# -*- coding: utf-8 -*-
"""Question_12_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gRrQEYqHsns-QIE3UUIFXeFl9Oh_jRFa
"""

import matplotlib.pyplot as plt

def plothistogram(data):
  plt.hist(data)
  plt.xlabel('Values')
  plt.ylabel('Frequency')
  plt.title('Histogram')
  plt.xlim(min(data)-1,max(data)+1)
  plt.show()

def main():
  n=int(input("Enter the size of list"))
  data=[]
  for i in range(0,n):
    val=int(input('Enter a value'))
    data.append(val)
  plothistogram(data)

if __name__=="__main__":
  main()