# -*- coding: utf-8 -*-
"""Question 10 python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mt9m_26Wlua09OeDJc7cHe24T9j5Ejnr
"""

def inp():
  str1=input("Enter the sentence : ")
  dict = {}
  for n in str1:
     keys = dict.keys()  
     if n in keys:
       dict[n] += 1
     else:
       dict[n] = 1
  print(dict)
inp()